### ISSUE TITLE
Use of FIX50SP2_EP194.xml in QuickFix/N

### ISSUE THREAD

**Issue by hadagali** [electronifie/quickfix-codegen#1]
Matt,
How can I use this file in QuickFix/N. Tried to generate the message obejcts using generate.rb but am getting the following error.

fields_gen.rb:34 'type_info' : field type not supported! TAGNUM (RuntimeError)

**Comment by mateodelnorte** [comment]
This is a standalone tool for creating fix libarary, based on an xml spec, in Node.js. You don't run it with other tools, and it only works with Node.js.

**Comment by mateodelnorte** [comment]
That said, if you would like to use it with Node.js, you can see how to create a library by looking at this example project: https://github.com/electronifie/fix-FIX50SP2_EP194-messages/blob/master/Makefile
